# Generated by Django 5.0.2 on 2024-02-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_ingredient_amount_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.TextField(max_length=64),
        ),
    ]
