version: '3'

volumes:
  pg_data_production:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    depends_on:
      - db
    image: hiho288/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
  frontend:
    depends_on:
      - backend
    image: hiho288/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: hiho288/foodgram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/var/media/
    ports:
      - 9000:80